import { Component } from ".";

export default {
  title: "Components/Component",
  component: Component,
  argTypes: {
    property1: {
      options: ["variant-2", "default"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    property1: "variant-2",
    className: {},
    overlapClassName: {},
    divClassName: {},
    overlapClassNameOverride: {},
    divClassNameOverride: {},
    overlapGroupClassName: {},
    divClassName1: {},
    overlapGroupClassNameOverride: {},
    divClassName2: {},
    overlapClassName1: {},
    divClassName3: {},
    overlapClassName2: {},
    divClassName4: {},
    overlapClassName3: {},
    divClassName5: {},
    overlapClassName4: {},
    overlapGroupClassName1: {},
    vectorClassName: {},
    vector: "/img/vector-243-1.svg",
    vectorClassNameOverride: {},
    img: "/img/vector-243-1.svg",
    imgClassName: {},
    vector1: "/img/vector-243-1.svg",
    imgClassNameOverride: {},
    vector2: "/img/vector-243-1.svg",
    vectorClassName1: {},
    vector3: "/img/vector-243-1.svg",
    vectorClassName2: {},
    vector4: "/img/vector-236.svg",
    groupClassName: {},
    ellipseClassName: {},
    ellipseClassNameOverride: {},
    ellipseClassName1: {},
    ellipseClassName2: {},
    ellipseClassName3: {},
    ellipseClassName4: {},
    ellipseClassName5: {},
    vectorClassName3: {},
    vector5: "/img/vector-235.svg",
    groupClassNameOverride: {},
    ellipseClassName6: {},
    ellipseClassName7: {},
    ellipseClassName8: {},
    ellipseClassName9: {},
    ellipseClassName10: {},
    ellipseClassName11: {},
    ellipseClassName12: {},
    vectorClassName4: {},
    vector6: "/img/vector-232-1.svg",
    vectorClassName5: {},
    vector7: "/img/vector-233-1.svg",
    vectorClassName6: {},
    vector8: "/img/vector-243-1.svg",
    divClassName6: {},
    divClassName7: {},
    divClassName8: {},
    divClassName9: {},
    divClassName10: {},
    divClassName11: {},
    divClassName12: {},
    divClassName13: {},
  },
};
