use master
IF DB_ID('SEBANK') IS NOT NULL
    DROP DATABASE SEBANK

GO
CREATE Database SEBANK

GO
use SEBANK

SET DATEFORMAT DMY
--Tạo bảng
DROP TABLE SOTIETKIEM
DROP TABLE LOAI_SOTK
DROP TABLE KHACHHANG
CREATE TABLE KHACHHANG (
	MAKH INT PRIMARY KEY,
	HOTEN NVARCHAR(100),
	DIACHI NVARCHAR(100),
	CMND CHAR(12) UNIQUE
)
CREATE TABLE LOAI_SOTK (
	MALOAI INT PRIMARY KEY, --KKH:0 --3M:3 --6M:6
	KYHAN NCHAR(20)
)
CREATE TABLE SOTIETKIEM (
	MASO CHAR(8) PRIMARY KEY,
	MAKH INT,
	SODU INT,
	LOAI INT, 
	NGAYMOSO DATE
)
ALTER TABLE SOTIETKIEM
ADD
	CONSTRAINT FK_SOTK_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG,

	CONSTRAINT FK_SOTK_LOAI
	FOREIGN KEY (LOAI)
	REFERENCES LOAI_SOTK
GO
--Thêm các loại tiết kiệm
INSERT LOAI_SOTK(MALOAI, KYHAN)
VALUES
	(0, N'KHÔNG KỲ HẠN'),
	(3, N'3 THÁNG'),
	(6, N'6 THÁNG')

--Tạo mã sổ mới
GO
CREATE OR ALTER FUNCTION dbo.TAO_MASO()
RETURNS CHAR(8)
AS
BEGIN
    DECLARE @MASO CHAR(8);

    SELECT @MASO = 'MS' + RIGHT('000000' + CAST(MAX(CAST(SUBSTRING(MASO, 3, 6) AS INT) + 1) AS VARCHAR(6)), 6)
    FROM SOTIETKIEM;
    RETURN @MASO;
END;
--Mở sổ tiết kiệm
GO
CREATE OR ALTER PROCEDURE MOSOTIETKIEM
	@LOAITK INT,
	@TENKH NVARCHAR(100),
	@CMND CHAR(12),
	@DIACHI NVARCHAR(100),
	@NGAYMOSO DATE,
	@SOTIEN INT
AS
BEGIN
	-- CHƯA KIỂM TRA TÍNH HỢP LỆ
	IF @LOAITK NOT IN (SELECT MALOAI FROM LOAI_SOTK)
		BEGIN
			RAISERROR(N'Loại tiết kiệm không hợp lệ', 16, 1);
			RETURN;  -- Dừng thực thi và thoát khỏi procedure
		END
	IF @NGAYMOSO < GETDATE() - 1
		BEGIN
			RAISERROR(N'Ngày mở sổ không hợp lệ', 16, 1);
			RETURN;  -- Dừng thực thi và thoát khỏi procedure
		END
	IF @SOTIEN < 100000 --DUNG BANG DE KIEM TRA SO TIEN TOI THIEU
		BEGIN
			RAISERROR(N'Số tiền gửi không hợp lệ', 16, 1);
			RETURN;  -- Dừng thực thi và thoát khỏi procedure
		END

	--Cập nhật bảng KHÁCH HÀNG
	DECLARE @MAKH INT;
	IF @CMND NOT IN (SELECT CMND FROM KHACHHANG)
		BEGIN
		IF (SELECT MAKH FROM KHACHHANG) IS NULL
			SET @MAKH = 0;
		ELSE SET @MAKH = (SELECT MAX(MAKH) FROM KHACHHANG) + 1 
		INSERT KHACHHANG(MAKH, HOTEN, DIACHI, CMND) VALUES (@MAKH, @TENKH, @DIACHI, @CMND);
		END
	ELSE
		SET @MAKH = (SELECT MAKH FROM KHACHHANG WHERE CMND = @CMND);
	
	--Cập nhật bảng SỔ TIẾT KIỆM
	DECLARE @MASO CHAR(8)
	IF (SELECT MASO FROM SOTIETKIEM) IS NULL
		SET @MASO = 'MS000000';
	ELSE SET @MASO = dbo.TAO_MASO();
	INSERT SOTIETKIEM(MASO, MAKH, SODU, LOAI, NGAYMOSO) VALUES (@MASO, @MAKH, @SOTIEN, @LOAITK, @NGAYMOSO)
	RETURN;
END
GO

--TEST
EXEC MOSOTIETKIEM 3,N'cường','01112122','aBC','19/07/2024',1000000
EXEC MOSOTIETKIEM 0,N'CUONG','0123123','aAC','18/07/2024',1000000
EXEC MOSOTIETKIEM 0,N'nghia','523123','aC','18/07/2024',1000000
SELECT * FROM KHACHHANG
SELECT * FROM SOTIETKIEM
SELECT * FROM LOAI_SOTK